// Auto-generated by scripts/generate-services.mjs from services/manifest.json.
// Real CRUD service — every route performs an actual Supabase call, no mocks.
// Re-running the generator will NOT touch this file if you convert it to a
// hero service with bespoke logic; delete it first if you want it regenerated.
const path = require('path');
const { createService, mountCrud, getSupabaseClient, start } = require(path.join(__dirname, '../_shared/serviceFactory'));

const { app } = createService("hr-service");
const supabase = getSupabaseClient();

mountCrud(app, { table: "employees", resource: "employees", idColumn: "id", supabase, defaultOrder: null });
mountCrud(app, { table: "leave_requests", resource: "leave-requests", idColumn: "id", supabase, defaultOrder: null });
mountCrud(app, { table: "leave_balances", resource: "leave-balances", idColumn: "id", supabase, defaultOrder: null });
mountCrud(app, { table: "clock_events", resource: "clock-events", idColumn: "id", supabase, defaultOrder: null });

start(app, "hr-service");
