// Auto-generated by scripts/generate-services.mjs from services/manifest.json.
// Real CRUD service — every route performs an actual Supabase call, no mocks.
// Re-running the generator will NOT touch this file if you convert it to a
// hero service with bespoke logic; delete it first if you want it regenerated.
const path = require('path');
const { createService, mountCrud, getSupabaseClient, start } = require(path.join(__dirname, '../_shared/serviceFactory'));

const { app } = createService("state-service");
const supabase = getSupabaseClient();

mountCrud(app, { table: "nx_module_state", resource: "module-state", idColumn: "module", supabase, defaultOrder: null });
mountCrud(app, { table: "nx_rate_limits", resource: "rate-limits", idColumn: "id", supabase, defaultOrder: null });

start(app, "state-service");
