#!/usr/bin/env node
// Generates the nginx load-balancer configs and docker-compose.yml from
// services/manifest.json. Re-run this after editing the manifest (adding a
// service, changing replica counts, etc.) instead of hand-editing the
// generated files — they are regenerated wholesale every run.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'services/manifest.json'), 'utf8'));
const gatewayPort = manifest.gatewayPort;

function containerPortFor() { return 4000; } // every container listens on 4000 internally

// ---------- nginx config for LOCAL execution (plain OS processes, no Docker) ----------
function buildNginxConf({ docker }) {
  const upstreams = manifest.services.map(svc => {
    const servers = Array.from({ length: svc.replicas }, (_, i) => {
      const host = docker ? `${svc.name}-${i + 1}` : '127.0.0.1';
      const port = docker ? containerPortFor() : svc.portBase + i;
      return `    server ${host}:${port} max_fails=2 fail_timeout=10s;`;
    }).join('\n');
    return `upstream ${svc.name} {\n    least_conn;\n${servers}\n}`;
  }).join('\n\n');

  const locations = manifest.services.map(svc => `
    location /api/${svc.resourcePrefix || svc.name.replace(/-service$/, '')}/ {
        rewrite ^/api/${svc.resourcePrefix || svc.name.replace(/-service$/, '')}/(.*)$ /$1 break;
        proxy_pass http://${svc.name};
        proxy_next_upstream error timeout http_502 http_503 http_504;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 2s;
    }`).join('\n');

  return `worker_processes 1;
error_log ${docker ? '/dev/stderr' : path.join(root, 'gateway/logs/error.log')} warn;
pid ${docker ? '/tmp/nginx.pid' : path.join(root, 'gateway/logs/nginx.pid')};

events { worker_connections 512; }

http {
  access_log ${docker ? '/dev/stdout' : path.join(root, 'gateway/logs/access.log')};
  sendfile on;

${upstreams}

  server {
    listen ${docker ? '0.0.0.0' : '127.0.0.1'}:${gatewayPort};
${locations}

    location /health {
      return 200 '{"status":"ok","service":"gateway"}';
      add_header Content-Type application/json;
    }

    location / {
      return 404 '{"error":"unknown_route"}';
      add_header Content-Type application/json;
    }
  }
}
`;
}

fs.mkdirSync(path.join(root, 'gateway/logs'), { recursive: true });
fs.writeFileSync(path.join(root, 'gateway/nginx.local.conf'), buildNginxConf({ docker: false }));
fs.writeFileSync(path.join(root, 'gateway/nginx.docker.conf'), buildNginxConf({ docker: true }));
console.log('wrote gateway/nginx.local.conf and gateway/nginx.docker.conf');

// ---------- docker-compose.yml (real deployment target) ----------
function composeServiceBlock(svc, replicaIndex) {
  const containerName = `${svc.name}-${replicaIndex + 1}`;
  return `  ${containerName}:
    build: ./services/${svc.name}
    container_name: ${containerName}
    environment:
      - PORT=4000
      - SUPABASE_URL=\${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=\${SUPABASE_SERVICE_ROLE_KEY}
      - GATEWAY_URL=http://gateway:${gatewayPort}
    restart: unless-stopped
    networks: [nexcore-net]
`;
}

let compose = `# Auto-generated by scripts/generate-infra.mjs from services/manifest.json.
# Run: docker compose up --build
# Requires a .env file with SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY (see .env.example).
services:
`;
for (const svc of manifest.services) {
  for (let i = 0; i < svc.replicas; i++) compose += composeServiceBlock(svc, i);
}
compose += `  gateway:
    image: nginx:1.27-alpine
    container_name: nexcore-gateway
    ports:
      - "${gatewayPort}:${gatewayPort}"
    volumes:
      - ./gateway/nginx.docker.conf:/etc/nginx/nginx.conf:ro
    depends_on:
${manifest.services.flatMap(svc => Array.from({ length: svc.replicas }, (_, i) => `      - ${svc.name}-${i + 1}`)).join('\n')}
    restart: unless-stopped
    networks: [nexcore-net]

networks:
  nexcore-net:
    driver: bridge
`;
fs.writeFileSync(path.join(root, 'docker-compose.yml'), compose);
console.log('wrote docker-compose.yml');

fs.writeFileSync(path.join(root, '.env.example'), `SUPABASE_URL=https://your-project.supabase.co
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key-here
`);
console.log('wrote .env.example');
